home:
 path: /
 controller: App\Controller\HomeController::index

dactylotest:
  path: /dactylotest
  controller: App\Controller\DactylotestController::main

savebenchmark:
  path: /benchmark/save
  controller: App\Controller\Admin\BenchmarkCrudController::save
